def options(ctx):
  pass
    
def configure(ctx):
  pass

def build(bld):
  bld.program(
       source       = 'test.cpp',
       target       = 'llfid',
       use          = 'LLFID PREFIXSUM',
       includes     = '.')
